
server:
  port: 8762
spring:
  application:
    name: sc-service-sample
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #默认true
    fetch-registry: true #默认true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
